/*
 * File: app/view/main/List.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PWA.view.main.List', {
    extend: 'Ext.dataview.List',
    alias: 'widget.main.list',

    requires: [
        'PWA.view.main.ListViewModel',
        'PWA.view.main.ListViewController',
        'Ext.dataview.pullrefresh.PullRefresh',
        'Ext.dataview.IndexBar',
        'Ext.XTemplate'
    ],

    controller: 'main.list',
    viewModel: {
        type: 'main.list'
    },
    cls: 'home-events',
    itemTpl: [
        '<div class="item-wrapper"> ',
        '    <div class="content"> ',
        '        <div class="picture large" style="background-image:url({picture})"></div> ',
        '        <div class="details"> ',
        '            <div class="person-name">{firstname} {lastname}</div> ',
        '            <div class="person-title">{title}</div> ',
        '        </div> ',
        '    </div> ',
        '</div>'
    ],
    loadingText: '',
    store: 'Personnel',
    itemConfig: {
        ui: 'cards',
        header: {
            ui: 'cards'
        }
    },
    grouped: true,
    infinite: true,

    plugins: [
        {
            pullText: 'Pull down to refresh',
            type: 'pullrefresh'
        }
    ],
    indexBar: {
        platformConfigs: {
            desktop: {
                autoHide: true
            },
            '!desktop': {
                autoHide: false
            }
        }
    },
    listeners: {
        childtap: 'onListChildtap'
    }

});