/*
 * File: app/view/main/MainViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PWA.view.main.MainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main.main',

    requires: [
        'Ext.route.Route'
    ],

    listen: {
        controller: {
            '*': {
                home: 'showList'
            }
        }
    },

    routes: {
        'home': 'showList',
        'person/:id': 'showPerson'
    },

    initViewModel: function() {
        Ext.getWin().on({
            scope: this,
            offline: 'onOffline',
            online: 'onOnline'
        });
    },

    onOffline: function() {
        var vm = this.getViewModel();

        vm.set('online', false);
    },

    onOnline: function() {
        var vm = this.getViewModel();

        vm.set('online', true);

        vm.get('personnel').reload();
    },

    waitForStore: function() {
        var view = this.getView(),
            vm = view.getViewModel(),
            store = vm.get('personnel');

        return new Ext.Promise(function (resolve, reject) {
            if (store.isLoaded()) {
                resolve();
            } else {
                store.on('load', resolve, this, { single: true });
            }
        });
    },

    onBackTap: function() {
        this.redirectTo(-1);
    },

    showList: function() {
        var view = this.getView(),
            vm = view.getViewModel();

        vm.set({
            title: 'Employee Directory'
        });

        view.setActiveItem(0);
    },

    showPerson: function(id) {

        this.waitForStore().then( () => {
            var view = this.getView(),
            list = this.lookup('person'),
            viewVm = view.getViewModel(),
            personVm = list.getViewModel(),
            store = viewVm.get('personnel'),
            record = store.getById(id);

            viewVm.set({
                title: 'Profile'
            });

            personVm.set({
                record: Ext.create('PWA.model.Person', record.data)
            });

            view.setActiveItem(list);
        });
    }

});