/*
 * File: app/view/person/Header.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    TODO: Bind time in personel-extra
*/
Ext.define('PWA.view.person.Header', {
    extend: 'Ext.Container',
    alias: 'widget.person.header',

    requires: [
        'PWA.view.person.HeaderViewModel',
        'Ext.Img',
        'Ext.XTemplate',
        'Ext.Container',
        'Ext.Button'
    ],

    viewModel: {
        type: 'person.header'
    },
    cls: 'person-header',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'image',
            userCls: 'picture',
            bind: {
                src: '{record.picture}'
            }
        },
        {
            xtype: 'component',
            userCls: 'person-info',
            tpl: [
                '<div class="person-name">{firstname} <b>{lastname}</b></div>',
                '<div class="person-title">{title}</div>'
            ],
            bind: {
                record: '{record}'
            }
        },
        {
            xtype: 'container',
            userCls: 'person-tools',
            layout: 'hbox',
            items: [
                {
                    xtype: 'button',
                    ui: 'action-phone',
                    iconCls: 'x-fa fa-phone',
                    bind: {
                        tooltip: 'Call <b>{record.phone}</b>'
                    },
                    listeners: {
                        tap: 'onCallTap'
                    }
                },
                {
                    xtype: 'button',
                    ui: 'action-skype',
                    iconCls: 'x-fa fa-skype',
                    bind: {
                        tooltip: 'Skype with <b>{record.skype}</b>'
                    },
                    listeners: {
                        tap: 'onSkypeTap'
                    }
                },
                {
                    xtype: 'button',
                    ui: 'action-email',
                    iconCls: 'x-fa fa-envelope',
                    bind: {
                        tooltip: 'Send email to <b>{record.email}</b>'
                    },
                    listeners: {
                        tap: 'onEmailTap'
                    }
                },
                {
                    xtype: 'button',
                    ui: 'action-linkedin',
                    iconCls: 'x-fa fa-linkedin',
                    bind: {
                        tooltip: 'See <b>{record.linkedin}</b> LinkedIn profile'
                    },
                    listeners: {
                        tap: 'onLinkedInTap'
                    }
                }
            ]
        },
        {
            xtype: 'component',
            flex: '1',
            userCls: 'person-extra',
            tpl: [
                '<div class="person-city"><i class="fa fa-map-marker"></i> {office.city}</div>',
                '<div class="person-time"><i class="fa fa-clock-o"></i> 11:00 pm</div>'
            ],
            bind: {
                record: '{record}'
            }
        }
    ],

    onCallTap: function(button, e, eOpts) {
        var vm = this.getViewModel(),
            record = vm.get('record');

        location = 'tel:' + record.get('email');
    },

    onSkypeTap: function(button, e, eOpts) {
        var vm = this.getViewModel(),
            record = vm.get('record');

        location = 'skype:' + record.get('skype') + '?call';
    },

    onEmailTap: function(button, e, eOpts) {

        var vm = this.getViewModel(),
            record = vm.get('record');

        location = 'mailto:' + record.get('email');
    },

    onLinkedInTap: function(button, e, eOpts) {
        var vm = this.getViewModel(),
            record = vm.get('record');

        window.open('https://www.linkedin.com/in/' + record.get('linkedin'), '_blank');
    }

});