/*
 * File: app/model/Person.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PWA.model.Person', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],


    fields: [
        {
            type: 'string',
            name: 'id'
        },
        {
            type: 'string',
            name: 'username'
        },
        {
            type: 'string',
            name: 'firstname'
        },
        {
            type: 'string',
            name: 'lastname'
        },
        {
            type: 'string',
            name: 'email'
        },
        {
            type: 'string',
            name: 'skype'
        },
        {
            type: 'string',
            name: 'linkedin'
        },
        {
            type: 'string',
            name: 'phone'
        },
        {
            type: 'string',
            name: 'extension'
        },
        {
            type: 'date',
            name: 'birthday',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'string',
            name: 'title'
        },
        {
            type: 'string',
            name: 'picture'
        },
        {
            type: 'date',
            name: 'started',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'date',
            name: 'ended',
            dateFormat: 'Y-m-d'
        },
        {
            name: 'office_id',
            reference: 'Office'
        },
        {
            name: 'organization_id',
            reference: 'Organization'
        },
        {
            calculate: function(data) {
                return data.firstname + ' ' + data.lastname;
            },
            name: 'fullname'
        }
    ]

});